# Repo of the action: https://github.com/IBM-Toolbox-Mexico-Public/fork-sync

name: AO IBM Fork Sync

on:
  push:
  schedule:
    - cron:  '59 23 * * 1-5' # Scheduled at 23:59 UTC every Monday and Friday
  workflow_dispatch:

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: IBM-Toolbox-Mexico-Public/fork-sync@v1.2 # Original repo: tgymnich/fork-sync@v1.2 (use if the action breaks)
        with:
          github_token: ${{ secrets.API_KEY }} # Use your own token in the repo secrets
          owner: Kong # Repo original owner (required)
          base: master # Head to sync from (default is master)
          head: master # Head to sync to (default is master)
